### ISSUE TITLE
Enable Set-Clipboard and Get-Clipboard aliases

### ISSUE THREAD

**Issue by gsacavdm** [mklement0/ClipboardText#6]
In PS, the commands included out of the box are Set-Clipboard and Get-Clipboard. PS Core doesn't have such commands out of the box but this awesome module makes that possible, however it does so with slightly different names.

In order to ensure I can run the same scripts in PS and PS Core without modifications and without extra branching logic, the clipboard commands should have the same name.

**Comment by mklement0** [comment]
Thanks, @gsacavdm, but I deliberately chose to avoid the names `Set-Clipboard` / `Get-Clipboard`, because the functions in the module at hand are not full replacements for the Windows PowerShell cmdlets bearing those names: this module's function can handle only _text_, whereas the latter can also handle _file objects_ (analogous to copying and pasting files in File Explorer), and `Get-Clipboard` can additionally retrieve image and audio data.

* If your scripts target PS Core only, there's no problem: you need to install/import this module anyway, and your scripts should then call `Set-ClipboardText` / `Get-ClipboardText`

* If your scripts target both PS Core and WinPS, and you don't want to install this module for the latter, you can do something like the following:

```powershell
if ($PSVersionTable.PSEdition -ne 'Core') {
  Set-Alias Set-ClipboardText Set-Clipboard
  Set-Alias Get-ClipboardText Get-Clipboard
}
```

**Comment by gsacavdm** [comment]
Hey @mklement0 , thank you for your response.

I assumed this was deliberate but wanted to confirm.

Did you also consider having an `Enable-ClipboardAlias` command that sets up the alias on their behalf similarly to what the new Az module does with the [Enable-AzureRmAlias](https://docs.microsoft.com/en-us/powershell/module/az.accounts/enable-azurermalias?view=azps-1.0.0)?

**Comment by mklement0** [comment]
Thanks for the suggestion, @gsacavdm, but given that we're only talking about 2 cmdlets, I'd rather not add another one just for enabling aliases.

**Comment by gsacavdm** [comment]
Good point. Thanks for taking the time to respond.
